#!/usr/bin/env python3
"""
fw_pack.py - wrap APP .bin with 12-byte header + CRC32, produce OTA firmware

Usage:
  python fw_pack.py                                # auto mode (double-click via fw_pack.bat)
  python fw_pack.py <input.bin> <version> [output]

Auto mode defaults:
  input  : <project>/Node/Firmware/Output/app.bin   (generated by Keil AfterBuild)
  version: auto-parsed from <project>/Node/Firmware/App/app_version.h  (FW_VERSION_STR "v2.1" -> 2.1)
  output : <project>/Node/Firmware/Output/app_fw.bin

Explicit mode keeps the original interface:
  python fw_pack.py Node/Firmware/Output/app.bin 2.2 Tool/app_fw.bin
"""

import struct, zlib, sys, os, re

FW_MAGIC = 0xA55A


def project_root():
    # this file is at <root>/Tool/fw_pack.py
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def auto_version():
    # single source: Node/Firmware/App/app_version.h (FW_VERSION_STR "X.Y")
    p = os.path.join(project_root(), 'Node', 'Firmware', 'App', 'app_version.h')
    try:
        with open(p, encoding='utf-8', errors='ignore') as f:
            text = f.read()
        m = re.search(r'FW_VERSION_STR\s+"v?(\d+)\.(\d+)"', text)
        if m:
            return '%s.%s' % (m.group(1), m.group(2))
    except OSError:
        pass
    return None


def pack_fw(input_path, version_str, output_path):
    with open(input_path, 'rb') as f:
        raw = f.read()

    parts = version_str.split('.')
    ver = (int(parts[0]) << 8) | int(parts[1]) if len(parts) >= 2 else int(parts[0])

    header = struct.pack('<HHII', FW_MAGIC, ver, len(raw), zlib.crc32(raw) & 0xFFFFFFFF)
    with open(output_path, 'wb') as f:
        f.write(header)
        f.write(raw)

    print('[OK] %s -> %s' % (input_path, output_path))
    print('     version  : 0x%04X (%s)' % (ver, version_str))
    print('     code len : %d bytes' % len(raw))
    print('     crc32    : 0x%08X' % (zlib.crc32(raw) & 0xFFFFFFFF))
    print('     total    : %d bytes' % (len(header) + len(raw)))


if __name__ == '__main__':
    root = project_root()

    if len(sys.argv) >= 3:
        in_path = sys.argv[1]
        version = sys.argv[2]
        out_path = sys.argv[3] if len(sys.argv) > 3 else os.path.join(root, 'Node', 'Firmware', 'Output', 'app_fw.bin')
    else:
        in_path = os.path.join(root, 'Node', 'Firmware', 'Output', 'app.bin')
        version = auto_version()
        out_path = os.path.join(root, 'Node', 'Firmware', 'Output', 'node_v%s.bin' % version)
        if version is None:
            print('[ERR] cannot auto-detect version from Node/Firmware/App/app_version.h')
            sys.exit(1)

    if not os.path.exists(in_path):
        print('[ERR] input not found: %s' % in_path)
        print('      -> build the APP project first (Keil AfterBuild generates app.bin)')
        sys.exit(1)

    pack_fw(in_path, version, out_path)
